# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CTe_sLpa2N_4VE0s2otw3C13gBlraY6k
"""

print("ANIKET BEDWAL")

name = 'Piyush'
print(f'Welcome To genzeon {name}')
aadhar = int(input('Enter aadhar card'))
print(f'{aadhar}')

c=7+5j
print(c.real)
print(c.imag)

#integer
a = 1
b = 4+5j

#float
c = 5.4

#text
s="hello"

#sequence type
my_list = [1,2,3,4]
my_tuple = (1,2,3,4)

#Mapping
dict={"name" : "aniket"}

#set
set1 = {1,2,3,4}

#boolean
x=true
y=float

a=3
b=4.3
c=float(a)
d= int(b)

print(c)

str = "     aniket"
str1 = str.upper()
print(str1)
str2 = str.lstrip()
print(str2)
dir(str)

str5 = " Aniket Bedwal"
print(str5.upper())
print(str5.title())
print(str5.rstrip())
print(str5.lstrip())
print(str5.swapcase())
print(str5.startswith('  '))
print(str5.ljust(10))